k8s_config:
- manifest_path: /manifests
  cluster_info:
    cluster_id: c53eff97-34a2-5fa1-9caf-0ba49cb1eecb
    cluster_name: AES Smoke Tests - Helm
- manifest_path: /manifests
  cluster_info:
    cluster_id: 505d1df6-dd9d-5c42-a331-11c74a6f1bb5
    cluster_name: AES Smoke Tests - Yaml
- manifest_path: /manifests
  cluster_info:
    cluster_id: 76fe7ad2-488f-55d8-b465-f12a33be1ff3
    cluster_name: Emissary Smoke Tests (Helm)
