k8s_config:
- manifest_path: /manifests
  cluster_info:
    cluster_id: c53eff97-34a2-5fa1-9caf-0ba49cb1eecb
    cluster_name: AES Smoke Tests - Helm
- manifest_path: /manifests
  cluster_info:
    cluster_id: 505d1df6-dd9d-5c42-a331-11c74a6f1bb5
    cluster_name: AES Smoke Tests - Yaml
- manifest_path: /manifest
  cluster_info:
    cluster_id: e0083f35-7d65-5c34-85c2-3ad29d2765ea
    cluster_name: AES Smoke Tests - Helm
